### ISSUE TITLE
fix styles settings

### ISSUE THREAD

**Issue by amjed-98** [GSG-G11/Quizzer#87]
- [ ] remove the custom breakpoints in client/src/theme.ts and to the material UI default breakpoints
- [ ] disable text-transform to all dom elements in the global styles file
 ```css 
* { text-transform: none !important; }
``` 

- [ ] disable text-decoration for anchor tags in the global styles file 
- [ ] add color prop value to be inherit to anchor tags
```css 
a { text-decoration: none; color: inherit }
```

- [ ] add CSS color variables in global styles file
```css 
:root {
  --primary: #4A6572;
  --secondary: #F9AA33;
  --secondary-light: #F9AA3350;
}
```
